name: Secret check single

on:
  push:
    branches: ["main"]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Print secret length (env)
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          echo "len:"
          echo "${DOCKERHUB_USERNAME}" | wc -c
